/**
 * Copyright (c) 2013-2014 Sascha Feldmann (sascha.feldmann@gmx.de) 
 */
package de.bht.fb6.s778455.bachelor.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import de.bht.fb6.s778455.bachelor.model.Tag.TagType;
import de.bht.fb6.s778455.bachelor.statistics.AStatisticsBuilder;

/**
 * <p>
 * StatisticsModels are generated by {@link AStatisticsBuilder}.
 * </p>
 * 
 * @author <a href="mailto:sascha.feldmann@gmx.de">Sascha Feldmann</a>
 * @since 09.01.2014
 * 
 */
public class StatisticsModel implements IDirectoryPortable, Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * Creation date of the statistics model.
     */
    protected Date dateCreation;

    /**
     * Number of given courses.
     */
    protected int numberCourses;
    /**
     * Number of given boards.
     */
    protected int numberBoards;
    /**
     * Number of given threads.
     */
    protected int numberThreads;
    /**
     * Number of given postings.
     */
    protected int numberPostings;

    /**
     * Number of postings which have Tags extracted by Topic Zoom.
     */
    protected int numberTopicZoomTaggedPostings;
    /**
     * Number of postings which have NER tags.
     */
    protected int numberNerTaggedPostings;
    /**
     * Number of postings which have at least one tag.
     */
    protected int numberTaggedPostings;

    /**
     * Number of {@link TopicZoomTag} instances.
     */
    protected int numberTopicZoomTags;
    /**
     * Number of {@link Tag} instances with {@link TagType} NER-Tag .
     */
    protected int numberNerTags;
    /**
     * Number of {@link Tag} instances with {@link TagType} POS-Tag .
     */
    protected int numberPosTags;
    /**
     * Number of {@link Tag} instances.
     */
    protected int numberTags;
    /**
     * Number of distinct {@link TopicZoomTag} tags. Distinct means: the URI and
     * the value are equal, so only count it once.
     */
    protected int numberDistinctTopicZoomTags;
    /**
     * Number of distinct {@link Tag} instances representing NER tags. Distinct
     * means: the URI and the value are equal, so only count it once.
     */
    protected int numberDistinctNerTags;
    /**
     * Number of distinct {@link Tag} instances representing POS tags. Distinct
     * means: the URI and the value are equal, so only count it once.
     */
    protected int numberDistinctPosTags;

    /**
     * Number of {@link Posting} instances which have both -
     * {@link TopicZoomTag} and {@link Tag} representing NER tags.
     */
    protected int numberTzAndNerTaggedPostings;

    /**
     * Number of {@link Course} with {@link TopicZoomTag}.
     */
    protected int numberTopicZoomTaggedCourses;
    /**
     * Number of {@link Board} with {@link TopicZoomTag}.
     */
    protected int numberTopicZoomTaggedBoards;
    /**
     * Number of {@link Course} with NER {@link Tag}.
     */
    protected int numberNerTaggedCourses;
    /**
     * Number of {@link Board} with NER {@link Tag}.
     */
    protected int numberNerTaggedBoards;
    /**
     * Number of {@link Course} with POS {@link Tag}.
     */
    protected int numberPosTaggedCourses;
    /**
     * Number of {@link Board} with POS {@link Tag}.
     */
    protected int numberPosTaggedBoards;
    /**
     * Number of {@link Posting} with POS {@link Tag}.
     */
    protected int numberPosTaggedPostings;
    
    /**
     * Number of {@link Course} with both Ner Tags and {@link TopicZoomTag}.
     */
    protected int numberTaggedCourses;
    /**
     * Number of {@link Board} with both Ner {@link Tag} and
     * {@link TopicZoomTag}.
     */
    protected int numberTaggedBoards;

    /**
     * Number of {@link Tag} which belong to {@link Board} instances.
     */
    protected int numberDistinctBoardTags;
    /**
     * Number of {@link Tag} belonging to {@link Course} instances.
     */
    protected int numberDistinctCourseTags;
    /**
     * Number of {@link Tag} belonging to {@link Posting} instances.
     */
    protected int numberDistinctPostingTags;

    /**
     * @return the numberTopicZoomTaggedCourses
     */
    public final int getNumberTopicZoomTaggedCourses() {
        return this.numberTopicZoomTaggedCourses;
    }

    /**
     * @param numberTopicZoomTaggedCourses
     *            the numberTopicZoomTaggedCourses to set
     */
    public final void setNumberTopicZoomTaggedCourses(
            final int numberTopicZoomTaggedCourses ) {
        this.numberTopicZoomTaggedCourses = numberTopicZoomTaggedCourses;
    }

    /**
     * @return the numberTopicZoomTaggedBoards
     */
    public final int getNumberTopicZoomTaggedBoards() {
        return this.numberTopicZoomTaggedBoards;
    }

    /**
     * @param numberTopicZoomTaggedBoards
     *            the numberTopicZoomTaggedBoards to set
     * @return
     */
    public final StatisticsModel setNumberTopicZoomTaggedBoards(
            final int numberTopicZoomTaggedBoards ) {
        this.numberTopicZoomTaggedBoards = numberTopicZoomTaggedBoards;

        return this;
    }

    /**
     * @return the numberNerTaggedCourses
     */
    public final int getNumberNerTaggedCourses() {
        return this.numberNerTaggedCourses;
    }

    /**
     * @param numberNerTaggedCourses
     *            the numberNerTaggedCourses to set
     * @return
     */
    public final StatisticsModel setNumberNerTaggedCourses(
            final int numberNerTaggedCourses ) {
        this.numberNerTaggedCourses = numberNerTaggedCourses;

        return this;
    }

    /**
     * @return the numberNerTaggedBoards
     */
    public final int getNumberNerTaggedBoards() {
        return this.numberNerTaggedBoards;
    }

    /**
     * @param numberNerTaggedBoards
     *            the numberNerTaggedBoards to set
     * @return
     */
    public final StatisticsModel setNumberNerTaggedBoards(
            final int numberNerTaggedBoards ) {
        this.numberNerTaggedBoards = numberNerTaggedBoards;

        return this;
    }

    /**
     * @return the numberTaggedCourses
     */
    public final int getNumberTaggedCourses() {
        return this.numberTaggedCourses;
    }

    /**
     * @param numberTaggedCourses
     *            the numberTaggedCourses to set
     * @return
     */
    public final StatisticsModel setNumberTaggedCourses(
            final int numberTaggedCourses ) {
        this.numberTaggedCourses = numberTaggedCourses;

        return this;
    }

    /**
     * @return the numberTaggedBoards
     */
    public final int getNumberTaggedBoards() {
        return this.numberTaggedBoards;
    }

    /**
     * @param numberTaggedBoards
     *            the numberTaggedBoards to set
     * @return
     */
    public final StatisticsModel setNumberTaggedBoards(
            final int numberTaggedBoards ) {
        this.numberTaggedBoards = numberTaggedBoards;

        return this;
    }

    /**
     * @return the numberBoardTags
     */
    public final int getDistinctNumberBoardTags() {
        return this.numberDistinctBoardTags;
    }

    /**
     * @param numberBoardTags
     *            the numberBoardTags to set
     * @return
     */
    public final StatisticsModel setDistinctNumberBoardTags(
            final int numberBoardTags ) {
        this.numberDistinctBoardTags = numberBoardTags;

        return this;
    }

    /**
     * @return the numberCourseTags
     */
    public final int getDistinctNumberCourseTags() {
        return this.numberDistinctCourseTags;
    }

    /**
     * @param numberCourseTags
     *            the numberCourseTags to set
     * @return
     */
    public final StatisticsModel setDistinctNumberCourseTags(
            final int numberCourseTags ) {
        this.numberDistinctCourseTags = numberCourseTags;

        return this;
    }

    /**
     * @return the numberPostingTags
     */
    public final int getDistinctNumberPostingTags() {
        return this.numberDistinctPostingTags;
    }

    /**
     * @param numberPostingTags
     *            the numberPostingTags to set
     * @return
     */
    public final StatisticsModel setDistinctNumberPostingTags(
            final int numberPostingTags ) {
        this.numberDistinctPostingTags = numberPostingTags;

        return this;
    }

    /**
     * {@link List} of all {@link Posting} which don't have any {@link Tag}.
     */
    protected List< Posting > untaggedPostings;

    /**
     * @return the dateCreation
     */
    public final Date getDateCreation() {
        return this.dateCreation;
    }

    /**
     * @param dateCreation
     *            the dateCreation to set
     * @return
     */
    public final StatisticsModel setDateCreation( final Date dateCreation ) {
        this.dateCreation = dateCreation;

        return this;
    }

    /**
     * @return the numberCourses
     */
    public final int getNumberCourses() {
        return this.numberCourses;
    }

    /**
     * @param numberCourses
     *            the numberCourses to set
     * @return
     */
    public final StatisticsModel setNumberCourses( final int numberCourses ) {
        this.numberCourses = numberCourses;

        return this;
    }

    /**
     * @return the numberBoards
     */
    public final int getNumberBoards() {
        return this.numberBoards;
    }

    /**
     * @param numberBoards
     *            the numberBoards to set
     * @return
     */
    public final StatisticsModel setNumberBoards( final int numberBoards ) {
        this.numberBoards = numberBoards;

        return this;
    }

    /**
     * @return the numberThreads
     */
    public final int getNumberThreads() {
        return this.numberThreads;
    }

    /**
     * @param numberThreads
     *            the numberThreads to set
     * @return
     */
    public final StatisticsModel setNumberThreads( final int numberThreads ) {
        this.numberThreads = numberThreads;

        return this;
    }

    /**
     * @return the numberPostings
     */
    public final int getNumberPostings() {
        return this.numberPostings;
    }

    /**
     * @param numberPostings
     *            the numberPostings to set
     * @return
     */
    public final StatisticsModel setNumberPostings( final int numberPostings ) {
        this.numberPostings = numberPostings;

        return this;
    }

    /**
     * @return the numberTopicZoomTaggedPostings
     */
    public final int getNumberTopicZoomTaggedPostings() {
        return this.numberTopicZoomTaggedPostings;
    }

    /**
     * @param numberTopicZoomTaggedPostings
     *            the numberTopicZoomTaggedPostings to set
     * @return
     */
    public final StatisticsModel setNumberTopicZoomTaggedPostings(
            final int numberTopicZoomTaggedPostings ) {
        this.numberTopicZoomTaggedPostings = numberTopicZoomTaggedPostings;

        return this;
    }

    /**
     * @return the numberNerTaggedPostings
     */
    public final int getNumberNerTaggedPostings() {
        return this.numberNerTaggedPostings;
    }

    /**
     * @param numberNerTaggedPostings
     *            the numberNerTaggedPostings to set
     * @return
     */
    public final StatisticsModel setNumberNerTaggedPostings(
            final int numberNerTaggedPostings ) {
        this.numberNerTaggedPostings = numberNerTaggedPostings;

        return this;
    }

    /**
     * @return the numberTaggedPostings
     */
    public final int getNumberTaggedPostings() {
        return this.numberTaggedPostings;
    }

    /**
     * @param numberTaggedPostings
     *            the numberTaggedPostings to set
     * @return
     */
    public final StatisticsModel setNumberTaggedPostings(
            final int numberTaggedPostings ) {
        this.numberTaggedPostings = numberTaggedPostings;

        return this;
    }

    public StatisticsModel setNumberTzAndNerTaggedPostings(
            final int numberPostingsTzAndNerTags ) {
        this.numberTzAndNerTaggedPostings = numberPostingsTzAndNerTags;

        return this;
    }

    /**
     * 
     * @return the number of postings which are both - NER and TopicZoom tagged.
     */
    public int getNumberTzAndNerTaggedPostings() {
        return this.numberNerTaggedPostings;
    }

    /**
     * @return the numberTopicZoomTags
     */
    public final int getNumberTopicZoomTags() {
        return this.numberTopicZoomTags;
    }

    /**
     * @param numberTopicZoomTags
     *            the numberTopicZoomTags to set
     * @return
     */
    public final StatisticsModel setNumberTopicZoomTags(
            final int numberTopicZoomTags ) {
        this.numberTopicZoomTags = numberTopicZoomTags;

        return this;
    }

    /**
     * @return the numberNerTags
     */
    public final int getNumberNerTags() {
        return this.numberNerTags;
    }

    /**
     * @param numberNerTags
     *            the numberNerTags to set
     * @return
     */
    public final StatisticsModel setNumberNerTags( final int numberNerTags ) {
        this.numberNerTags = numberNerTags;

        return this;
    }

    /**
     * @return the numberTags
     */
    public final int getNumberTags() {
        return this.numberTags;
    }

    /**
     * @param numberTags
     *            the numberTags to set
     * @return
     */
    public final StatisticsModel setNumberTags( final int numberTags ) {
        this.numberTags = numberTags;

        return this;
    }

    /**
     * @return the numberDistinctTopicZoomTags
     */
    public final int getNumberDistinctTopicZoomTags() {
        return this.numberDistinctTopicZoomTags;
    }

    /**
     * @param numberDistinctTopicZoomTags
     *            the numberDistinctTopicZoomTags to set
     * @return
     */
    public final StatisticsModel setNumberDistinctTopicZoomTags(
            final int numberDistinctTopicZoomTags ) {
        this.numberDistinctTopicZoomTags = numberDistinctTopicZoomTags;

        return this;
    }

    /**
     * @return the numberDistinctNerTags
     */
    public final int getNumberDistinctNerTags() {
        return this.numberDistinctNerTags;
    }

    /**
     * @param numberDistinctNerTags
     *            the numberDistinctNerTags to set
     * @return
     */
    public final StatisticsModel setNumberDistinctNerTags(
            final int numberDistinctNerTags ) {
        this.numberDistinctNerTags = numberDistinctNerTags;

        return this;
    }

    /**
     * @return the untaggedPostings
     */
    public final List< Posting > getUntaggedPostings() {
        return this.untaggedPostings;
    }

    /**
     * @param untaggedPostings
     *            the untaggedPostings to set
     * @return
     */
    public final StatisticsModel setUntaggedPostings(
            final List< Posting > untaggedPostings ) {
        this.untaggedPostings = untaggedPostings;

        return this;
    }

    /**
     * @return the numberPosTags
     */
    public final int getNumberPosTags() {
        return this.numberPosTags;
    }

    /**
     * @param numberPosTags the numberPosTags to set
     * @return 
     */
    public final StatisticsModel setNumberPosTags( final int numberPosTags ) {
        this.numberPosTags = numberPosTags;
        
        return this;
    }

    /**
     * @return the numberPosTaggedCourses
     */
    public final int getNumberPosTaggedCourses() {
        return this.numberPosTaggedCourses;
    }

    /**
     * @param numberPosTaggedCourses the numberPosTaggedCourses to set
     * @return 
     */
    public final StatisticsModel setNumberPosTaggedCourses( final int numberPosTaggedCourses ) {
        this.numberPosTaggedCourses = numberPosTaggedCourses;
        
        return this;
    }

    /**
     * @return the numberPosTaggedBoards
     */
    public final int getNumberPosTaggedBoards() {
        return this.numberPosTaggedBoards;
    }

    /**
     * @param numberPosTaggedBoards the numberPosTaggedBoards to set
     * @return 
     */
    public final StatisticsModel setNumberPosTaggedBoards( final int numberPosTaggedBoards ) {
        this.numberPosTaggedBoards = numberPosTaggedBoards;
        
        return this;
    }

    /**
     * @return the numberPosTaggedPostings
     */
    public final int getNumberPosTaggedPostings() {
        return this.numberPosTaggedPostings;
    }

    /**
     * @param numberPosTaggedPostings the numberPosTaggedPostings to set
     * @return 
     */
    public final StatisticsModel setNumberPosTaggedPostings( final int numberPosTaggedPostings ) {
        this.numberPosTaggedPostings = numberPosTaggedPostings;
        
        return this;
    }

    /**
     * @return the numberDistinctPosTags
     */
    public final int getNumberDistinctPosTags() {
        return this.numberDistinctPosTags;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime
                * result
                + ( ( this.dateCreation == null ) ? 0 : this.dateCreation
                        .hashCode() );
        result = prime * result + this.numberDistinctBoardTags;
        result = prime * result + this.numberBoards;
        result = prime * result + this.numberDistinctCourseTags;
        result = prime * result + this.numberCourses;
        result = prime * result + this.numberDistinctNerTags;
        result = prime * result + this.numberDistinctTopicZoomTags;
        result = prime * result + this.numberNerTaggedBoards;
        result = prime * result + this.numberNerTaggedCourses;
        result = prime * result + this.numberNerTaggedPostings;
        result = prime * result + this.numberNerTags;
        result = prime * result + this.numberDistinctPostingTags;
        result = prime * result + this.numberPostings;
        result = prime * result + this.numberTaggedBoards;
        result = prime * result + this.numberTaggedCourses;
        result = prime * result + this.numberTaggedPostings;
        result = prime * result + this.numberTags;
        result = prime * result + this.numberThreads;
        result = prime * result + this.numberTopicZoomTaggedBoards;
        result = prime * result + this.numberTopicZoomTaggedCourses;
        result = prime * result + this.numberTopicZoomTaggedPostings;
        result = prime * result + this.numberTopicZoomTags;
        result = prime * result + this.numberTzAndNerTaggedPostings;
        result = prime
                * result
                + ( ( this.untaggedPostings == null ) ? 0
                        : this.untaggedPostings.hashCode() );
        return result;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals( final Object obj ) {
        if( this == obj )
            return true;
        if( obj == null )
            return false;
        if( this.getClass() != obj.getClass() )
            return false;
        final StatisticsModel other = ( StatisticsModel ) obj;
        if( this.dateCreation == null ) {
            if( other.dateCreation != null )
                return false;
        } else if( !this.dateCreation.equals( other.dateCreation ) )
            return false;
        if( this.numberDistinctBoardTags != other.numberDistinctBoardTags )
            return false;
        if( this.numberBoards != other.numberBoards )
            return false;
        if( this.numberDistinctCourseTags != other.numberDistinctCourseTags )
            return false;
        if( this.numberCourses != other.numberCourses )
            return false;
        if( this.numberDistinctNerTags != other.numberDistinctNerTags )
            return false;
        if( this.numberDistinctTopicZoomTags != other.numberDistinctTopicZoomTags )
            return false;
        if( this.numberNerTaggedBoards != other.numberNerTaggedBoards )
            return false;
        if( this.numberNerTaggedCourses != other.numberNerTaggedCourses )
            return false;
        if( this.numberNerTaggedPostings != other.numberNerTaggedPostings )
            return false;
        if( this.numberNerTags != other.numberNerTags )
            return false;
        if( this.numberDistinctPostingTags != other.numberDistinctPostingTags )
            return false;
        if( this.numberPostings != other.numberPostings )
            return false;
        if( this.numberTaggedBoards != other.numberTaggedBoards )
            return false;
        if( this.numberTaggedCourses != other.numberTaggedCourses )
            return false;
        if( this.numberTaggedPostings != other.numberTaggedPostings )
            return false;
        if( this.numberTags != other.numberTags )
            return false;
        if( this.numberThreads != other.numberThreads )
            return false;
        if( this.numberTopicZoomTaggedBoards != other.numberTopicZoomTaggedBoards )
            return false;
        if( this.numberTopicZoomTaggedCourses != other.numberTopicZoomTaggedCourses )
            return false;
        if( this.numberTopicZoomTaggedPostings != other.numberTopicZoomTaggedPostings )
            return false;
        if( this.numberTopicZoomTags != other.numberTopicZoomTags )
            return false;
        if( this.numberTzAndNerTaggedPostings != other.numberTzAndNerTaggedPostings )
            return false;
        if( this.untaggedPostings == null ) {
            if( other.untaggedPostings != null )
                return false;
        } else if( !this.untaggedPostings.equals( other.untaggedPostings ) )
            return false;
        return true;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        final StringBuilder builder = new StringBuilder();
        builder.append( "StatisticsModel [getNumberTopicZoomTaggedCourses()=" );
        builder.append( this.getNumberTopicZoomTaggedCourses() );
        builder.append( ", getNumberTopicZoomTaggedBoards()=" );
        builder.append( this.getNumberTopicZoomTaggedBoards() );
        builder.append( ", getNumberNerTaggedCourses()=" );
        builder.append( this.getNumberNerTaggedCourses() );
        builder.append( ", getNumberNerTaggedBoards()=" );
        builder.append( this.getNumberNerTaggedBoards() );
        builder.append( ", getNumberTaggedCourses()=" );
        builder.append( this.getNumberTaggedCourses() );
        builder.append( ", getNumberTaggedBoards()=" );
        builder.append( this.getNumberTaggedBoards() );
        builder.append( ", getNumberBoardTags()=" );
        builder.append( this.getDistinctNumberBoardTags() );
        builder.append( ", getNumberCourseTags()=" );
        builder.append( this.getDistinctNumberCourseTags() );
        builder.append( ", getNumberPostingTags()=" );
        builder.append( this.getDistinctNumberPostingTags() );
        builder.append( ", getDateCreation()=" );
        builder.append( this.getDateCreation() );
        builder.append( ", getNumberCourses()=" );
        builder.append( this.getNumberCourses() );
        builder.append( ", getNumberBoards()=" );
        builder.append( this.getNumberBoards() );
        builder.append( ", getNumberThreads()=" );
        builder.append( this.getNumberThreads() );
        builder.append( ", getNumberPostings()=" );
        builder.append( this.getNumberPostings() );
        builder.append( ", getNumberTopicZoomTaggedPostings()=" );
        builder.append( this.getNumberTopicZoomTaggedPostings() );
        builder.append( ", getNumberNerTaggedPostings()=" );
        builder.append( this.getNumberNerTaggedPostings() );
        builder.append( ", getNumberTaggedPostings()=" );
        builder.append( this.getNumberTaggedPostings() );
        builder.append( ", getNumberTzAndNerTaggedPostings()=" );
        builder.append( this.getNumberTzAndNerTaggedPostings() );
        builder.append( ", getNumberTopicZoomTags()=" );
        builder.append( this.getNumberTopicZoomTags() );
        builder.append( ", getNumberNerTags()=" );
        builder.append( this.getNumberNerTags() );
        builder.append( ", getNumberTags()=" );
        builder.append( this.getNumberTags() );
        builder.append( ", getNumberDistinctTopicZoomTags()=" );
        builder.append( this.getNumberDistinctTopicZoomTags() );
        builder.append( ", getNumberDistinctNerTags()=" );
        builder.append( this.getNumberDistinctNerTags() );
        builder.append( "]" );
        return builder.toString();
    }

    @Override
    public String exportToTxt() {
        return this.toString();
    }

    @Override
    public void importFromTxt( final String key, final String value ) {
        throw new UnsupportedOperationException(
                "importFromTxt() is not supported. Use serialization instead." );
    }

    public StatisticsModel setNumberDistinctPosTags(
            final int numberDistinctPosTags ) {
        this.numberDistinctPosTags = numberDistinctPosTags;
        return this;
    }

}
